### ISSUE TITLE
Assign story values on sprint backlog

### ISSUE THREAD

**Issue by Eric-Jestel** [COS420-Fall24/TeamG#31]
Product Backlog ( /10)  

Use [this template](https://docs.google.com/spreadsheets/d/1422Rr_2YRKFydVoz7m8bNor666bmfIwj/edit?usp=sharing&ouid=108788083057609121398&rtpof=true&sd=true). See [example(s) here](https://docs.google.com/document/d/137-bYw-6sKMvgCOt0Oe0FOXApaL8dif0XzVZpSDdLTw/edit?usp=share_link).

Product backlog and sprint backlog should match i.e. product backlog items in the sprint backlog need to have the same IDs etc. If they do not match deduct -2 points.

Make sure that all of your user stories are in the product backlog. For any missing user story deduct -1 point.

All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.

**Comment by JoshWilbur** [comment]
Use fibonacci numbers up to 8 for this. So a "1" is a very small task and an 8 is a hard/long task. If we believe a task is greater than an 8, we should try to break it down.
